export const actionType = {
  FETCH_PRODUCT_LIST: 'FETCH_PRODUCT_LIST',
  FETCH_PRODUCT_LIST_SUCCESS: 'FETCH_PRODUCT_LIST_SUCCESS',
  FETCH_PRODUCT_LIST_FAILED: 'FETCH_PRODUCT_LIST_FAILED',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_ONE_ITEM_FROM_CART: 'REMOVE_ONE_ITEM_FROM_CART'
}

